version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --local-infile=ON
    ports:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass

  setup:
    build: .
    image: acris-setup
    #ACRIS_DATASET: mysql, mysql_real_complete, mysql_personal, mysql_personal_complete, mysql_extras
    #See Makefile for latest MySQL options
    command: make ${ACRIS_DATASET:-mysql} HOST=db USER=root PASS=pass
    volumes:
      - ./docker/mysql/client/my.cnf:/etc/mysql/my.cnf
      - ./data/downloads:/app/data
    depends_on:
      - db

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db
